import { test, expect } from '@playwright/test';

// Test configuration
const BASE_URL = 'http://localhost:9903';
const EXAMPLES = [
  { path: '/pages/', name: 'Index Page' },
  { path: '/pages/00-quick-start.html', name: 'Quick Start' },
  { path: '/pages/01-components.html', name: 'Components' },
  { path: '/pages/02-tables.html', name: 'Tables' },
  { path: '/pages/02-forms.html', name: 'Forms' },
  { path: '/pages/03-styling.html', name: 'Styling' },
  { path: '/pages/04-dashboard.html', name: 'Dashboard' },
  { path: '/pages/05-state.html', name: 'State' },
  { path: '/pages/06-tic-tac-toe-tutorial.html', name: 'Tic Tac Toe Tutorial' }
];

// Visual regression test for each page
EXAMPLES.forEach(({ path, name }) => {
  test.describe(`${name} - Visual & Functional Tests`, () => {
    test.beforeEach(async ({ page }) => {
      await page.goto(`${BASE_URL}${path}`);
      // Wait for page to fully load
      await page.waitForLoadState('networkidle');
    });

    test('should have proper styling and layout', async ({ page }) => {
      // Check main content area exists (#app is the mount point for all dogfooded pages)
      const appMount = page.locator('#app');
      await expect(appMount).toBeVisible();

      // Check content-container is rendered (generated by TACO)
      const mainContent = page.locator('.content-container').first();
      await expect(mainContent).toBeVisible();

      // Check font family
      const fontFamily = await page.evaluate(() =>
        window.getComputedStyle(document.body).fontFamily
      );
      expect(fontFamily).toContain('system-ui');

      // Take screenshot for visual regression
      await page.screenshot({
        path: `test/screenshots/${name.toLowerCase().replace(/\s+/g, '-')}-full.png`,
        fullPage: true
      });
    });

    test('should have responsive design', async ({ page }) => {
      // Test mobile viewport
      await page.setViewportSize({ width: 375, height: 667 });
      await page.waitForTimeout(500);

      // Content should not overflow horizontally
      const bodyOverflow = await page.evaluate(() => {
        return document.body.scrollWidth > window.innerWidth + 5; // 5px tolerance
      });
      expect(bodyOverflow).toBeFalsy();

      // Test tablet viewport
      await page.setViewportSize({ width: 768, height: 1024 });
      await page.waitForTimeout(500);

      // Test desktop viewport
      await page.setViewportSize({ width: 1920, height: 1080 });
      await page.waitForTimeout(500);
    });

    test('should have proper color contrast', async ({ page }) => {
      // Check text contrast ratios for visible text elements
      const contrastResults = await page.evaluate(() => {
        const getContrast = (rgb1, rgb2) => {
          const getLuminance = (r, g, b) => {
            const [rs, gs, bs] = [r, g, b].map(c => {
              c = c / 255;
              return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
            });
            return 0.2126 * rs + 0.7152 * gs + 0.0722 * bs;
          };

          const parseRgb = (rgb) => {
            const match = rgb.match(/\d+/g);
            return match ? match.map(Number) : [0, 0, 0];
          };

          const [r1, g1, b1] = parseRgb(rgb1);
          const [r2, g2, b2] = parseRgb(rgb2);

          const l1 = getLuminance(r1, g1, b1);
          const l2 = getLuminance(r2, g2, b2);

          const lighter = Math.max(l1, l2);
          const darker = Math.min(l1, l2);

          return (lighter + 0.05) / (darker + 0.05);
        };

        // Walk up the DOM to find the actual background color (skip transparent)
        // Returns { bg, hasGradient } — hasGradient=true means a gradient/image bg was found
        const getEffectiveBg = (el) => {
          let current = el;
          while (current && current !== document.documentElement) {
            const styles = window.getComputedStyle(current);
            // Check for gradient or background-image first
            const bgImage = styles.backgroundImage;
            if (bgImage && bgImage !== 'none') {
              return { bg: null, hasGradient: true };
            }
            const bg = styles.backgroundColor;
            if (bg && bg !== 'rgba(0, 0, 0, 0)' && bg !== 'transparent') {
              return { bg, hasGradient: false };
            }
            current = current.parentElement;
          }
          return { bg: 'rgb(255, 255, 255)', hasGradient: false }; // default white
        };

        const results = [];
        const elements = document.querySelectorAll('h1, h2, h3, p');

        elements.forEach(el => {
          // Skip hidden elements
          if (el.offsetParent === null && el.style.position !== 'fixed') return;

          const styles = window.getComputedStyle(el);
          const { bg, hasGradient } = getEffectiveBg(el);

          // Skip elements on gradient/image backgrounds (can't extract color)
          if (hasGradient) return;

          const color = styles.color;
          const contrast = getContrast(color, bg);

          results.push({
            selector: el.tagName.toLowerCase() + (el.className ? '.' + el.className.split(' ')[0] : ''),
            contrast,
            passes: contrast >= 4.5 // WCAG AA standard
          });
        });

        return results;
      });

      // All visible text should pass contrast requirements
      const failedContrast = contrastResults.filter(r => !r.passes);
      expect(failedContrast).toHaveLength(0);
    });
  });
});

// Specific functional tests for interactive components
test.describe('Interactive Components', () => {
  test('Tic Tac Toe game should be playable', async ({ page }) => {
    await page.goto(`${BASE_URL}/pages/06-tic-tac-toe-tutorial.html`);
    await page.waitForLoadState('networkidle');

    // Find game boards (step-based, not #final-game)
    const gameBoards = page.locator('.game-board');
    const boardCount = await gameBoards.count();
    expect(boardCount).toBeGreaterThanOrEqual(1);

    // Find the last (most advanced) game board
    const lastBoard = gameBoards.last();
    await lastBoard.scrollIntoViewIfNeeded();
    await expect(lastBoard).toBeVisible();

    // Check it has 9 squares
    const squares = lastBoard.locator('.square');
    await expect(squares).toHaveCount(9);

    // Click a square to verify interactivity
    await squares.first().click();
  });

  test('Table sorting should work correctly', async ({ page }) => {
    await page.goto(`${BASE_URL}/pages/02-tables.html`);
    await page.waitForLoadState('networkidle');

    // Find interactive table
    await page.waitForSelector('#interactive-table-container table');
    const table = page.locator('#interactive-table-container table');
    await expect(table).toBeVisible();

    // Click on a sortable header
    const headers = table.locator('thead th');
    const headerCount = await headers.count();
    expect(headerCount).toBeGreaterThan(1);

    // Click Name header (index 2, after checkbox and # columns)
    const nameHeader = headers.nth(2);
    await nameHeader.click();

    // Get first row name
    const firstName = await table.locator('tbody tr').first().locator('td').nth(2).textContent();

    // Click again to reverse sort
    await nameHeader.click();

    // Verify order changed
    const newFirstName = await table.locator('tbody tr').first().locator('td').nth(2).textContent();
    expect(firstName).not.toBe(newFirstName);
  });

  test('Theme preview should be interactive', async ({ page }) => {
    await page.goto(`${BASE_URL}/pages/03-styling.html`);
    await page.waitForLoadState('networkidle');

    // Find theme preview area
    const themePreview = page.locator('#theme-preview-area');
    await expect(themePreview).toBeVisible();

    // Check color inputs exist
    const colorInputs = page.locator('input[type="color"]');
    const colorCount = await colorInputs.count();
    expect(colorCount).toBeGreaterThanOrEqual(2);
  });
});

// Performance tests
test.describe('Performance', () => {
  test('Pages should load quickly', async ({ page }) => {
    const metrics = [];

    for (const { path, name } of EXAMPLES) {
      await page.goto(`${BASE_URL}${path}`);

      const performanceTiming = await page.evaluate(() =>
        JSON.parse(JSON.stringify(window.performance.timing))
      );

      const loadTime = performanceTiming.loadEventEnd - performanceTiming.navigationStart;

      metrics.push({
        page: name,
        loadTime,
        domReady: performanceTiming.domContentLoadedEventEnd - performanceTiming.navigationStart
      });

      // Page should load in under 3 seconds
      expect(loadTime).toBeLessThan(3000);
    }

    console.table(metrics);
  });

  test('DOM updates should be efficient', async ({ page }) => {
    await page.goto(`${BASE_URL}/pages/06-tic-tac-toe-tutorial.html`);
    await page.waitForLoadState('networkidle');

    // Find a game board to test click performance
    const gameBoard = page.locator('.game-board').last();
    await gameBoard.scrollIntoViewIfNeeded();

    const squares = gameBoard.locator('.square');
    await expect(squares).toHaveCount(9);

    // Measure click responsiveness
    const renderMetrics = await page.evaluate(async () => {
      const boards = document.querySelectorAll('.game-board');
      const board = boards[boards.length - 1];
      const squares = board.querySelectorAll('.square');

      const start = performance.now();

      // Simulate clicks on squares
      for (let i = 0; i < Math.min(squares.length, 9); i++) {
        squares[i].click();
      }

      const end = performance.now();

      return {
        totalTime: end - start,
        averageTime: (end - start) / 9
      };
    });

    // Average render time should be under 10ms
    expect(renderMetrics.averageTime).toBeLessThan(10);
  });
});

// Accessibility tests
test.describe('Accessibility', () => {
  test('All images should have alt text', async ({ page }) => {
    await page.goto(`${BASE_URL}/pages/01-components.html`);
    await page.waitForLoadState('networkidle');

    const imagesWithoutAlt = await page.evaluate(() => {
      const images = Array.from(document.querySelectorAll('img'));
      // Exclude decorative SVGs and icons that use role="presentation"
      return images
        .filter(img => !img.alt && img.getAttribute('role') !== 'presentation')
        .map(img => img.src);
    });

    expect(imagesWithoutAlt).toHaveLength(0);
  });

  test('Forms should have proper labels', async ({ page }) => {
    await page.goto(`${BASE_URL}/pages/02-forms.html`);
    await page.waitForLoadState('networkidle');

    // Check that form groups have labels
    const formGroups = page.locator('.bw_form_group');
    const groupCount = await formGroups.count();
    expect(groupCount).toBeGreaterThan(0);

    // Each form group should have a label
    const firstGroup = formGroups.first();
    const label = firstGroup.locator('label');
    await expect(label).toBeVisible();
  });

  test('Interactive elements should be keyboard accessible', async ({ page }) => {
    await page.goto(`${BASE_URL}/pages/01-components.html`);

    // Tab through page
    await page.keyboard.press('Tab');

    // Check focused element is visible
    const focusedElement = await page.evaluate(() => {
      const el = document.activeElement;
      return {
        tag: el.tagName,
        visible: el.offsetParent !== null
      };
    });

    expect(focusedElement.visible).toBeTruthy();
  });
});

// CSS and styling tests
test.describe('CSS and Styling', () => {
  test('Custom CSS properties should be applied', async ({ page }) => {
    await page.goto(`${BASE_URL}/pages/`);
    await page.waitForLoadState('networkidle');

    // Check CSS variables are defined
    const cssVars = await page.evaluate(() => {
      const styles = getComputedStyle(document.documentElement);
      return {
        primary: styles.getPropertyValue('--bw_primary').trim(),
        secondary: styles.getPropertyValue('--bw_secondary').trim(),
        success: styles.getPropertyValue('--bw_success').trim()
      };
    });

    // Bitwrench should define these variables
    expect(cssVars.primary).toBeTruthy();
  });

  test('Components should have consistent spacing', async ({ page }) => {
    await page.goto(`${BASE_URL}/pages/01-components.html`);
    await page.waitForLoadState('networkidle');

    const spacings = await page.evaluate(() => {
      const cards = Array.from(document.querySelectorAll('.bw_card'));
      return cards.map(card => {
        const styles = window.getComputedStyle(card);
        return {
          padding: styles.padding,
          margin: styles.margin
        };
      });
    });

    // Should have cards
    expect(spacings.length).toBeGreaterThan(0);

    // All cards should have same padding
    const firstSpacing = spacings[0];
    spacings.forEach(spacing => {
      expect(spacing.padding).toBe(firstSpacing.padding);
    });
  });
});
