import { test, expect } from '@playwright/test';

// All pages use baseURL from playwright.config.js (http://localhost:8081)
const EXAMPLES = [
  { path: '/pages/', name: 'Index Page' },
  { path: '/pages/00-quick-start.html', name: 'Quick Start' },
  { path: '/pages/01-components.html', name: 'Components' },
  { path: '/pages/02-tables-forms.html', name: 'Tables & Forms' },
  { path: '/pages/03-styling.html', name: 'Styling' },
  { path: '/pages/04-dashboard.html', name: 'Dashboard' },
  { path: '/pages/05-state.html', name: 'State' },
  { path: '/pages/06-tic-tac-toe-tutorial.html', name: 'Tic Tac Toe Tutorial' },
  { path: '/pages/06-clock.html', name: 'Clock' },
  { path: '/pages/07-framework-comparison.html', name: 'Framework Comparison' },
  { path: '/pages/08-api-reference.html', name: 'API Reference' },
  { path: '/pages/09-downloads.html', name: 'Downloads' },
  { path: '/pages/10-themes.html', name: 'Themes' },
  { path: '/pages/11-debugging.html', name: 'Debugging' },
  { path: '/pages/12-bwserve-protocol.html', name: 'bwserve Protocol' }
];

// Visual regression test for each page
EXAMPLES.forEach(({ path, name }) => {
  test.describe(`${name} - Visual & Functional Tests`, () => {
    test.beforeEach(async ({ page }) => {
      await page.goto(path);
      await page.waitForLoadState('networkidle');
    });

    test('should have proper styling and layout', async ({ page }) => {
      // Check main content area exists — pages may use #app or render directly into .content-container
      const appMount = page.locator('#app, .content-container').first();
      await expect(appMount).toBeVisible();

      // Check content-container is rendered (generated by TACO or present in HTML)
      const mainContent = page.locator('.content-container').first();
      await expect(mainContent).toBeVisible();

      // Check font family
      const fontFamily = await page.evaluate(() =>
        window.getComputedStyle(document.body).fontFamily
      );
      expect(fontFamily).toContain('system-ui');

      // Take screenshot for visual regression
      await page.screenshot({
        path: `test/screenshots/${name.toLowerCase().replace(/\s+/g, '-')}-full.png`,
        fullPage: true
      });
    });

    test('should have responsive mobile layout (375px)', async ({ page }) => {
      await page.setViewportSize({ width: 375, height: 667 });
      await page.waitForTimeout(500);

      // 1. No horizontal overflow (15px tolerance for scrollbar/rounding)
      const bodyOverflow = await page.evaluate(() =>
        document.body.scrollWidth > window.innerWidth + 15
      );
      expect(bodyOverflow).toBeFalsy();

      // 2. Hamburger menu visible (nav collapses at 900px)
      const hamburger = page.locator('.bw_site_nav_hamburger');
      if (await hamburger.count() > 0) {
        await expect(hamburger.first()).toBeVisible();
      }

      // 3. Desktop nav links hidden
      const navLinks = page.locator('.bw_site_nav_links');
      if (await navLinks.count() > 0) {
        await expect(navLinks.first()).not.toBeVisible();
      }

      // 4. Tables should not cause page-level horizontal overflow.
      // A table is OK if it fits, or if any ancestor (up to body) clips/scrolls it.
      const tableOverflow = await page.evaluate(() => {
        const tables = document.querySelectorAll('.bw_table, .bw-table, table');
        const results = [];
        tables.forEach(table => {
          if (table.offsetParent === null) return; // skip hidden
          const fits = table.scrollWidth <= window.innerWidth + 5;
          if (fits) { results.push({ ok: true }); return; }
          // Walk ancestors looking for overflow containment
          let el = table.parentElement;
          let contained = false;
          while (el && el !== document.body) {
            const s = window.getComputedStyle(el);
            const ox = s.overflowX;
            if (ox === 'auto' || ox === 'scroll' || ox === 'hidden') {
              contained = true;
              break;
            }
            el = el.parentElement;
          }
          results.push({ ok: contained });
        });
        return results;
      });
      tableOverflow.forEach(t => {
        expect(t.ok).toBeTruthy();
      });

      // 5. Cards stack vertically (no two cards at same Y position)
      const cardPositions = await page.evaluate(() => {
        const cards = Array.from(document.querySelectorAll('.bw_card, .bw-card'));
        // Only check visible cards
        return cards
          .filter(c => c.offsetParent !== null)
          .map(c => {
            const rect = c.getBoundingClientRect();
            return { top: Math.round(rect.top), left: Math.round(rect.left), width: Math.round(rect.width) };
          });
      });
      // If there are multiple cards, check no two occupy the same row
      // (i.e. side-by-side). Two cards are side-by-side if their tops are
      // within 10px AND their left values differ.
      for (let i = 0; i < cardPositions.length; i++) {
        for (let j = i + 1; j < cardPositions.length; j++) {
          const a = cardPositions[i], b = cardPositions[j];
          const sameRow = Math.abs(a.top - b.top) < 10;
          const sideBySide = sameRow && Math.abs(a.left - b.left) > 20;
          if (sideBySide) {
            // Allow if both cards are narrow enough to fit side-by-side
            // (e.g. in a deliberate 2-col layout that still fits in 375px)
            const totalWidth = a.width + b.width;
            expect(totalWidth).toBeLessThanOrEqual(375 + 20); // 20px tolerance
          }
        }
      }

      // 6. Code blocks contained (pre scrollWidth <= parent clientWidth + tolerance)
      const codeOverflow = await page.evaluate(() => {
        const pres = document.querySelectorAll('pre');
        const overflowing = [];
        pres.forEach(pre => {
          if (pre.offsetParent === null) return; // skip hidden
          const parent = pre.parentElement;
          if (parent && pre.scrollWidth > parent.clientWidth + 10) {
            const parentOverflow = window.getComputedStyle(parent).overflowX;
            const preOverflow = window.getComputedStyle(pre).overflowX;
            // OK if pre or parent has scroll/auto overflow
            if (preOverflow !== 'auto' && preOverflow !== 'scroll' &&
                parentOverflow !== 'auto' && parentOverflow !== 'scroll') {
              overflowing.push({
                text: pre.textContent.substring(0, 40),
                scrollW: pre.scrollWidth,
                parentW: parent.clientWidth
              });
            }
          }
        });
        return overflowing;
      });
      expect(codeOverflow).toHaveLength(0);

      // 7. Form inputs: text/email/textarea should not be tiny on mobile
      const inputWidths = await page.evaluate(() => {
        // Only check full-width candidates (text, email, search, textarea)
        const inputs = document.querySelectorAll(
          'input[type="text"], input[type="email"], input[type="search"], textarea'
        );
        const results = [];
        inputs.forEach(input => {
          if (input.offsetParent === null) return; // skip hidden
          const rect = input.getBoundingClientRect();
          // Must be at least 100px wide to be usable on mobile
          results.push({ width: Math.round(rect.width) });
        });
        return results;
      });
      inputWidths.forEach(r => {
        expect(r.width).toBeGreaterThanOrEqual(100);
      });
    });

    test('should have responsive tablet layout (768px)', async ({ page }) => {
      await page.setViewportSize({ width: 768, height: 1024 });
      await page.waitForTimeout(500);

      // No horizontal overflow
      const bodyOverflow = await page.evaluate(() =>
        document.body.scrollWidth > window.innerWidth + 5
      );
      expect(bodyOverflow).toBeFalsy();

      // Nav hamburger still showing at 768px (breakpoint is 900px)
      const hamburger = page.locator('.bw_site_nav_hamburger');
      if (await hamburger.count() > 0) {
        await expect(hamburger.first()).toBeVisible();
      }

      // Desktop nav links still hidden at 768px
      const navLinks = page.locator('.bw_site_nav_links');
      if (await navLinks.count() > 0) {
        await expect(navLinks.first()).not.toBeVisible();
      }
    });

    test('should have proper color contrast', async ({ page }) => {
      // Check text contrast ratios for visible text elements
      const contrastResults = await page.evaluate(() => {
        const getContrast = (rgb1, rgb2) => {
          const getLuminance = (r, g, b) => {
            const [rs, gs, bs] = [r, g, b].map(c => {
              c = c / 255;
              return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
            });
            return 0.2126 * rs + 0.7152 * gs + 0.0722 * bs;
          };

          const parseRgb = (rgb) => {
            const match = rgb.match(/\d+/g);
            return match ? match.map(Number) : [0, 0, 0];
          };

          const [r1, g1, b1] = parseRgb(rgb1);
          const [r2, g2, b2] = parseRgb(rgb2);

          const l1 = getLuminance(r1, g1, b1);
          const l2 = getLuminance(r2, g2, b2);

          const lighter = Math.max(l1, l2);
          const darker = Math.min(l1, l2);

          return (lighter + 0.05) / (darker + 0.05);
        };

        // Walk up the DOM to find the actual background color (skip transparent)
        const getEffectiveBg = (el) => {
          let current = el;
          while (current && current !== document.documentElement) {
            const styles = window.getComputedStyle(current);
            const bgImage = styles.backgroundImage;
            if (bgImage && bgImage !== 'none') {
              return { bg: null, hasGradient: true };
            }
            const bg = styles.backgroundColor;
            if (bg && bg !== 'rgba(0, 0, 0, 0)' && bg !== 'transparent') {
              return { bg, hasGradient: false };
            }
            current = current.parentElement;
          }
          return { bg: 'rgb(255, 255, 255)', hasGradient: false };
        };

        // Classes that intentionally use muted/secondary text (WCAG AA large-text 3:1 OK)
        const mutedClasses = ['build-meta', 'text-muted', 'text-secondary', 'bw_text_muted', 'bw-text-muted', 'subtitle', 'page-subtitle'];

        const results = [];
        const elements = document.querySelectorAll('h1, h2, h3, p');

        elements.forEach(el => {
          if (el.offsetParent === null && el.style.position !== 'fixed') return;

          const isMuted = mutedClasses.some(cls => el.classList.contains(cls));

          const styles = window.getComputedStyle(el);
          const { bg, hasGradient } = getEffectiveBg(el);

          if (hasGradient) return;

          const color = styles.color;
          const contrast = getContrast(color, bg);
          // WCAG AA: 4.5:1 normal text, 3:1 large text (>=18px or >=14px bold)
          const fontSize = parseFloat(styles.fontSize);
          const fontWeight = parseInt(styles.fontWeight, 10) || 400;
          const isLargeText = fontSize >= 18 || (fontSize >= 14 && fontWeight >= 700);
          const threshold = (isMuted || isLargeText) ? 3.0 : 4.5;

          results.push({
            selector: el.tagName.toLowerCase() + (el.className ? '.' + el.className.split(' ')[0] : ''),
            contrast,
            passes: contrast >= threshold
          });
        });

        return results;
      });

      const failedContrast = contrastResults.filter(r => !r.passes);
      expect(failedContrast).toHaveLength(0);
    });
  });
});

// Specific functional tests for interactive components
test.describe('Interactive Components', () => {
  test('Tic Tac Toe game should be playable', async ({ page }) => {
    await page.goto('/pages/06-tic-tac-toe-tutorial.html');
    await page.waitForLoadState('networkidle');

    const gameBoards = page.locator('.game-board');
    const boardCount = await gameBoards.count();
    expect(boardCount).toBeGreaterThanOrEqual(1);

    const lastBoard = gameBoards.last();
    await lastBoard.scrollIntoViewIfNeeded();
    await expect(lastBoard).toBeVisible();

    const squares = lastBoard.locator('.square');
    await expect(squares).toHaveCount(9);

    await squares.first().click();
  });

  test('Table sorting should work correctly', async ({ page }) => {
    await page.goto('/pages/02-tables-forms.html');
    await page.waitForLoadState('networkidle');

    await page.waitForSelector('#interactive-table-container table', { timeout: 10000 });
    const table = page.locator('#interactive-table-container table');
    await expect(table).toBeVisible();

    const headers = table.locator('thead th');
    const headerCount = await headers.count();
    expect(headerCount).toBeGreaterThan(1);

    const nameHeader = headers.nth(2);
    await nameHeader.click();

    const firstName = await table.locator('tbody tr').first().locator('td').nth(2).textContent();

    await nameHeader.click();

    const newFirstName = await table.locator('tbody tr').first().locator('td').nth(2).textContent();
    expect(firstName).not.toBe(newFirstName);
  });

  test('Theme preview should be interactive', async ({ page }) => {
    await page.goto('/pages/03-styling.html');
    await page.waitForLoadState('networkidle');

    const themePreview = page.locator('#theme-preview-area');
    await expect(themePreview).toBeVisible();

    const colorInputs = page.locator('input[type="color"]');
    const colorCount = await colorInputs.count();
    expect(colorCount).toBeGreaterThanOrEqual(2);
  });
});

// Performance tests
test.describe('Performance', () => {
  test('Pages should load quickly', async ({ page }) => {
    const metrics = [];

    for (const { path, name } of EXAMPLES) {
      await page.goto(path);

      const performanceTiming = await page.evaluate(() =>
        JSON.parse(JSON.stringify(window.performance.timing))
      );

      const loadTime = performanceTiming.loadEventEnd - performanceTiming.navigationStart;

      metrics.push({
        page: name,
        loadTime,
        domReady: performanceTiming.domContentLoadedEventEnd - performanceTiming.navigationStart
      });

      expect(loadTime).toBeLessThan(3000);
    }

    console.table(metrics);
  });

  test('DOM updates should be efficient', async ({ page }) => {
    await page.goto('/pages/06-tic-tac-toe-tutorial.html');
    await page.waitForLoadState('networkidle');

    const gameBoard = page.locator('.game-board').last();
    await gameBoard.scrollIntoViewIfNeeded();

    const squares = gameBoard.locator('.square');
    await expect(squares).toHaveCount(9);

    const renderMetrics = await page.evaluate(async () => {
      const boards = document.querySelectorAll('.game-board');
      const board = boards[boards.length - 1];
      const squares = board.querySelectorAll('.square');

      const start = performance.now();

      for (let i = 0; i < Math.min(squares.length, 9); i++) {
        squares[i].click();
      }

      const end = performance.now();

      return {
        totalTime: end - start,
        averageTime: (end - start) / 9
      };
    });

    expect(renderMetrics.averageTime).toBeLessThan(10);
  });
});

// Accessibility tests
test.describe('Accessibility', () => {
  test('All images should have alt text', async ({ page }) => {
    await page.goto('/pages/01-components.html');
    await page.waitForLoadState('networkidle');

    const imagesWithoutAlt = await page.evaluate(() => {
      const images = Array.from(document.querySelectorAll('img'));
      return images
        .filter(img => !img.alt && img.getAttribute('role') !== 'presentation')
        .map(img => img.src);
    });

    expect(imagesWithoutAlt).toHaveLength(0);
  });

  test('Forms should have proper labels', async ({ page }) => {
    await page.goto('/pages/02-tables-forms.html');
    await page.waitForLoadState('networkidle');

    // Forms are generated dynamically by bw.makeFormGroup() -- check for rendered form groups
    const formGroups = page.locator('.bw_form_group, .bw-form-group');
    const groupCount = await formGroups.count();
    expect(groupCount).toBeGreaterThan(0);

    const firstGroup = formGroups.first();
    const label = firstGroup.locator('label');
    await expect(label).toBeVisible();
  });

  test('Interactive elements should be keyboard accessible', async ({ page }) => {
    await page.goto('/pages/01-components.html');

    await page.keyboard.press('Tab');

    const focusedElement = await page.evaluate(() => {
      const el = document.activeElement;
      return {
        tag: el.tagName,
        visible: el.offsetParent !== null
      };
    });

    expect(focusedElement.visible).toBeTruthy();
  });
});

// CSS and styling tests
test.describe('CSS and Styling', () => {
  test('Bitwrench-generated styles should be applied', async ({ page }) => {
    await page.goto('/pages/');
    await page.waitForLoadState('networkidle');

    // Pages inject CSS via bw.css() + bw.injectCSS() — verify styles are present
    const styleInfo = await page.evaluate(() => {
      const bodyStyle = getComputedStyle(document.body);
      // Count injected <style> elements (bitwrench injects CSS this way)
      const styleElements = document.querySelectorAll('style');
      return {
        fontFamily: bodyStyle.fontFamily,
        styleCount: styleElements.length
      };
    });

    expect(styleInfo.fontFamily).toContain('system-ui');
    expect(styleInfo.styleCount).toBeGreaterThan(0);
  });

  test('Components should have consistent spacing', async ({ page }) => {
    await page.goto('/pages/01-components.html');
    await page.waitForLoadState('networkidle');

    // Check cards within a single section (cards section) have consistent padding
    // Different component sections may intentionally use different card padding
    const spacings = await page.evaluate(() => {
      var section = document.querySelector('#section-cards');
      if (!section) return [];
      var cards = Array.from(section.querySelectorAll('.bw_card, .bw-card'));
      return cards.map(function(card) {
        var styles = window.getComputedStyle(card);
        return {
          padding: styles.padding,
          margin: styles.margin
        };
      });
    });

    expect(spacings.length).toBeGreaterThan(0);

    var firstSpacing = spacings[0];
    spacings.forEach(function(spacing) {
      expect(spacing.padding).toBe(firstSpacing.padding);
    });
  });

  test('Themed components should remain responsive at 375px', async ({ page }) => {
    await page.goto('/pages/01-components.html');
    await page.waitForLoadState('networkidle');

    // Generate a custom theme on the page
    await page.evaluate(() => {
      if (typeof bw !== 'undefined' && bw.loadStyles) {
        bw.loadStyles({
          primary: '#336699',
          secondary: '#cc6633'
        });
      }
    });

    // Switch to mobile viewport
    await page.setViewportSize({ width: 375, height: 667 });
    await page.waitForTimeout(500);

    // Theme CSS must not break layout — no horizontal overflow
    const bodyOverflow = await page.evaluate(() =>
      document.body.scrollWidth > window.innerWidth + 5
    );
    expect(bodyOverflow).toBeFalsy();

    // Cards should still stack properly under theme
    const cardPositions = await page.evaluate(() => {
      const cards = Array.from(document.querySelectorAll('.bw_card, .bw-card'));
      return cards
        .filter(c => c.offsetParent !== null)
        .map(c => {
          const rect = c.getBoundingClientRect();
          return { top: Math.round(rect.top), width: Math.round(rect.width) };
        });
    });
    cardPositions.forEach(c => {
      // Each card should be roughly viewport width (not half-width side-by-side)
      if (c.width > 50) { // skip tiny cards
        expect(c.width).toBeLessThanOrEqual(375 + 5);
      }
    });
  });
});
