#travis configuration for coverage testing of bitwrench
# M A Chatterjee 2018-07-05

language: node_js
node_js:
  - "13"
dist: trusty # needs Ubuntu Trusty
# Note: if you switch to sudo: false, you'll need to launch Chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: required
addons:
  chrome: stable # have Travis install Chrome stable.
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm
script:
  - npm run testkarma


#language: node_js
#node_js:
#  - "4.0.0"
#
#before_install:
#  - npm install coveralls
#
#after_success: npm run coveralls
#
#branches:
#  only:
#    - master