/**
 * bwclient.js — Browser-side protocol client for bwserve.
 *
 * Injected inline by bwshell. Requires window.bw (bitwrench loaded first).
 * NOT bundled into bitwrench dist — this is a bwserve runtime asset.
 *
 * Responsibilities:
 * - SSE connection lifecycle (connect, reconnect, status)
 * - Unified POST-back via /bw/return/<route>/<clientId>
 * - Register built-in client functions (scrollTo, focus, etc.)
 * - bw_act_* class click/key delegation
 * - Attach mode for remote-controlling any bitwrench page
 *
 * @module bwserve/bwclient
 */

import { VERSION } from '../version.js';

/**
 * Return the bwclient source as a string for inline injection into the shell.
 * The version is embedded at serve-time from package.json via version.js.
 * @returns {string} JavaScript source code
 */
export function getBwClientSource() {
  return BWCLIENT_SOURCE.replace('__BW_VERSION__', VERSION);
}

var BWCLIENT_SOURCE = '(function(bw) {\n'
  + '  "use strict";\n'
  + '  if (!bw) return;\n'
  + '\n'
  + '  var _client = {\n'
  + '    id: null,\n'
  + '    version: "__BW_VERSION__",\n'
  + '    status: "idle",\n'
  + '    _es: null\n'
  + '  };\n'
  + '\n'
  + '  // ── Unified POST-back ──\n'
  + '  _client.respond = function(route, requestId, result, error) {\n'
  + '    var base = (typeof origin !== "undefined" ? origin : "");\n'
  + '    fetch(base + "/bw/return/" + route + "/" + _client.id, {\n'
  + '      method: "POST",\n'
  + '      headers: { "Content-Type": "application/json" },\n'
  + '      body: JSON.stringify({ requestId: requestId, route: route, result: result, error: error || null })\n'
  + '    }).catch(function(e) { console.warn("[bwclient] respond failed:", e); });\n'
  + '  };\n'
  + '\n'
  + '  // ── SSE connect ──\n'
  + '  _client.connect = function(url, opts) {\n'
  + '    opts = opts || {};\n'
  + '    var onStatus = opts.onStatus || function() {};\n'
  + '    function setStatus(s) { _client.status = s; onStatus(s); }\n'
  + '    setStatus("connecting");\n'
  + '    if (typeof EventSource === "undefined") return;\n'
  + '    var es = new EventSource(url);\n'
  + '    _client._es = es;\n'
  + '    es.onopen = function() { setStatus("connected"); };\n'
  + '    es.onmessage = function(e) {\n'
  + '      try {\n'
  + '        var msg = typeof e.data === "string" ? bw.parseJSONFlex(e.data) : e.data;\n'
  + '        bw.apply(msg);\n'
  + '      } catch (err) {\n'
  + '        if (typeof console !== "undefined") console.error("[bwclient]", err);\n'
  + '      }\n'
  + '    };\n'
  + '    es.onerror = function() {\n'
  + '      if (_client.status === "connected") setStatus("disconnected");\n'
  + '    };\n'
  + '  };\n'
  + '\n'
  + '  // ── Attach mode ──\n'
  + '  _client.attach = function(url, opts) {\n'
  + '    opts = opts || {};\n'
  + '    _client.id = opts.clientId || "att_" + Math.random().toString(36).slice(2, 10);\n'
  + '    _client._registerBuiltins();\n'
  + '    _client._wireActions();\n'
  + '    _client.connect(url + "/bw/events/" + _client.id, opts);\n'
  + '  };\n'
  + '\n'
  + '  // ── Send action to server ──\n'
  + '  _client.sendAction = function(action, data) {\n'
  + '    _client.respond("action", null, { action: action, data: data || {} });\n'
  + '  };\n'
  + '\n'
  + '  // ── Register built-in functions (safe closures, no string eval) ──\n'
  + '  _client._registerBuiltins = function() {\n'
  + '    bw.registerRemote("scrollTo", function(sel) {\n'
  + '      var el = bw.el(sel); if (el) el.scrollTop = el.scrollHeight;\n'
  + '    });\n'
  + '    bw.registerRemote("focus", function(sel) {\n'
  + '      var el = bw.el(sel); if (el && typeof el.focus === "function") el.focus();\n'
  + '    });\n'
  + '    bw.registerRemote("download", function(fn, c, m) {\n'
  + '      if (typeof document === "undefined") return;\n'
  + '      var b = new Blob([c], { type: m || "text/plain" });\n'
  + '      var a = document.createElement("a");\n'
  + '      a.href = URL.createObjectURL(b); a.download = fn; a.click();\n'
  + '      URL.revokeObjectURL(a.href);\n'
  + '    });\n'
  + '    bw.registerRemote("clipboard", function(t) {\n'
  + '      if (typeof navigator !== "undefined" && navigator.clipboard) navigator.clipboard.writeText(t);\n'
  + '    });\n'
  + '    bw.registerRemote("redirect", function(u) {\n'
  + '      if (typeof window !== "undefined") window.location.href = u;\n'
  + '    });\n'
  + '    bw.registerRemote("log", function() {\n'
  + '      console.log.apply(console, arguments);\n'
  + '    });\n'
  + '    bw.registerRemote("_bw_mount", function(opts) {\n'
  + '      if (!bw._bwClient) return;\n'
  + '      try {\n'
  + '        var f = opts.factory;\n'
  + '        var n = f.replace(/-([a-z])/g, function(_, c) { return c.toUpperCase(); });\n'
  + '        if (bw.BCCL && bw.BCCL[n]) {\n'
  + '          var taco = bw.make(n, opts.props || {});\n'
  + '          bw.mount(opts.target, taco);\n'
  + '          bw._bwClient.respond("mount", opts.requestId, { mounted: true });\n'
  + '        } else {\n'
  + '          throw new Error("Unknown BCCL component: " + f);\n'
  + '        }\n'
  + '      } catch (e) {\n'
  + '        bw._bwClient.respond("mount", opts.requestId, null, e.message);\n'
  + '      }\n'
  + '    });\n'
  + '    bw.registerRemote("_bw_screenshot", function(opts) {\n'
  + '      if (!bw._bwClient) return;\n'
  + '      var sel = opts.selector || "body";\n'
  + '      var el = document.querySelector(sel);\n'
  + '      if (!el) { bw._bwClient.respond("screenshot", opts.requestId, null, "Element not found: " + sel); return; }\n'
  + '      function _ls(url) {\n'
  + '        return new Promise(function(res, rej) {\n'
  + '          var s = document.createElement("script"); s.src = url;\n'
  + '          s.onload = function() { res(window.html2canvas); };\n'
  + '          s.onerror = function() { rej(new Error("Failed to load html2canvas")); };\n'
  + '          document.head.appendChild(s);\n'
  + '        });\n'
  + '      }\n'
  + '      var p = window.html2canvas ? Promise.resolve(window.html2canvas) : _ls(opts.captureUrl || "/bw/lib/vendor/html2canvas.min.js");\n'
  + '      p.then(function(h2c) { return h2c(el, { scale: opts.scale || 1, useCORS: true }); })\n'
  + '       .then(function(canvas) {\n'
  + '         var out = canvas;\n'
  + '         var mw = opts.maxWidth; var mh = opts.maxHeight;\n'
  + '         if ((mw && canvas.width > mw) || (mh && canvas.height > mh)) {\n'
  + '           var sw = mw ? mw / canvas.width : 1; var sh = mh ? mh / canvas.height : 1;\n'
  + '           var sc = Math.min(sw, sh);\n'
  + '           out = document.createElement("canvas");\n'
  + '           out.width = Math.round(canvas.width * sc); out.height = Math.round(canvas.height * sc);\n'
  + '           out.getContext("2d").drawImage(canvas, 0, 0, out.width, out.height);\n'
  + '         }\n'
  + '         var fmt = opts.format === "jpeg" ? "image/jpeg" : "image/png";\n'
  + '         var q = opts.format === "jpeg" ? (opts.quality || 0.85) : undefined;\n'
  + '         var dataUrl = out.toDataURL(fmt, q);\n'
  + '         bw._bwClient.respond("screenshot", opts.requestId, { data: dataUrl, width: out.width, height: out.height, format: opts.format || "png" });\n'
  + '       }).catch(function(err) {\n'
  + '         bw._bwClient.respond("screenshot", opts.requestId, null, err.message || String(err));\n'
  + '       });\n'
  + '    });\n'
  + '    bw.registerRemote("_bw_tree", function(opts) {\n'
  + '      if (!bw._bwClient) return;\n'
  + '      var sel = opts.selector || "body"; var depth = opts.depth || 3;\n'
  + '      var root = document.querySelector(sel);\n'
  + '      if (typeof bw.inspect === "function" && bw.inspect.length === 2) {\n'
  + '        bw._bwClient.respond("query", opts.requestId, bw.inspect(root, depth)); return;\n'
  + '      }\n'
  + '      function walk(el, d) {\n'
  + '        if (!el || d > depth) return null;\n'
  + '        var info = { tag: el.tagName ? el.tagName.toLowerCase() : "#text" };\n'
  + '        if (el.id) info.id = el.id;\n'
  + '        if (el.className && typeof el.className === "string") info.cls = el.className.split(" ").slice(0, 5).join(" ");\n'
  + '        if (el.children && el.children.length > 0 && d < depth) {\n'
  + '          info.children = [];\n'
  + '          for (var i = 0; i < Math.min(el.children.length, 20); i++) {\n'
  + '            var c = walk(el.children[i], d + 1); if (c) info.children.push(c);\n'
  + '          }\n'
  + '        }\n'
  + '        return info;\n'
  + '      }\n'
  + '      bw._bwClient.respond("query", opts.requestId, walk(root, 0));\n'
  + '    });\n'
  + '    bw.registerRemote("_bw_query", function(opts) {\n'
  + '      if (!bw._bwClient) return;\n'
  + '      try {\n'
  + '        var result;\n'
  + '        try { result = new Function("return (" + opts.code + ")")(); }\n'
  + '        catch (se) { result = new Function(opts.code)(); }\n'
  + '        bw._bwClient.respond("query", opts.requestId, result !== undefined ? result : null);\n'
  + '      } catch (e) {\n'
  + '        bw._bwClient.respond("query", opts.requestId, null, e.message || String(e));\n'
  + '      }\n'
  + '    });\n'
  + '    bw.registerRemote("_bw_listen", function(opts) {\n'
  + '      if (!bw._bwClient) return;\n'
  + '      if (!bw._bwClient._listeners) bw._bwClient._listeners = {};\n'
  + '      var key = opts.selector + ":::" + opts.event;\n'
  + '      if (bw._bwClient._listeners[key]) return;\n'
  + '      var fn = function(e) {\n'
  + '        var el = e.target.closest ? e.target.closest(opts.selector) : null;\n'
  + '        if (!el) return;\n'
  + '        bw._bwClient.respond("event", null, {\n'
  + '          event: opts.event, selector: opts.selector, tagName: el.tagName,\n'
  + '          id: el.id || null, text: (el.textContent || "").slice(0, 100)\n'
  + '        });\n'
  + '      };\n'
  + '      document.addEventListener(opts.event, fn, true);\n'
  + '      bw._bwClient._listeners[key] = { fn: fn, event: opts.event };\n'
  + '    });\n'
  + '    bw.registerRemote("_bw_unlisten", function(opts) {\n'
  + '      if (!bw._bwClient || !bw._bwClient._listeners) return;\n'
  + '      var key = opts.selector + ":::" + opts.event;\n'
  + '      var entry = bw._bwClient._listeners[key];\n'
  + '      if (!entry) return;\n'
  + '      document.removeEventListener(entry.event, entry.fn, true);\n'
  + '      delete bw._bwClient._listeners[key];\n'
  + '    });\n'
  + '  };\n'
  + '\n'
  + '  // ── Wire up action click delegation via bw_act_* classes ──\n'
  + '  _client._wireActions = function() {\n'
  + '    document.addEventListener("click", function(e) {\n'
  + '      var el = e.target;\n'
  + '      var action = null;\n'
  + '      while (el && el !== document) {\n'
  + '        if (el.classList) {\n'
  + '          for (var i = 0; i < el.classList.length; i++) {\n'
  + '            if (el.classList[i].indexOf("bw_act_") === 0) {\n'
  + '              action = el.classList[i].substring(7);\n'
  + '              break;\n'
  + '            }\n'
  + '          }\n'
  + '        }\n'
  + '        if (action) break;\n'
  + '        el = el.parentElement;\n'
  + '      }\n'
  + '      if (!action) return;\n'
  + '      e.preventDefault();\n'
  + '      var actionData = {};\n'
  + '      if (el.id) actionData.id = el.id;\n'
  + '      var form = el.closest ? (el.closest("div") || document) : document;\n'
  + '      var inp = form.querySelector("input[type=text],input:not([type])");\n'
  + '      if (inp) { actionData.inputValue = inp.value; inp.value = ""; }\n'
  + '      _client.sendAction(action, actionData);\n'
  + '    });\n'
  + '    document.addEventListener("keydown", function(e) {\n'
  + '      if (e.key === "Enter" && e.target.tagName === "INPUT") {\n'
  + '        var form = e.target.closest ? (e.target.closest("div") || document) : document;\n'
  + '        var btn = null;\n'
  + '        var els = form.querySelectorAll("[class*=bw_act_]");\n'
  + '        if (els.length) btn = els[0];\n'
  + '        var action = null;\n'
  + '        if (btn && btn.classList) {\n'
  + '          for (var i = 0; i < btn.classList.length; i++) {\n'
  + '            if (btn.classList[i].indexOf("bw_act_") === 0) {\n'
  + '              action = btn.classList[i].substring(7);\n'
  + '              break;\n'
  + '            }\n'
  + '          }\n'
  + '          if (action) {\n'
  + '            _client.sendAction(action, { inputValue: e.target.value });\n'
  + '            e.target.value = "";\n'
  + '          }\n'
  + '        }\n'
  + '      }\n'
  + '    });\n'
  + '  };\n'
  + '\n'
  + '  // ── Wire bw.remote for server communication ──\n'
  + '  bw.remote = {\n'
  + '    send: function(msg) { _client.respond("action", null, msg); }\n'
  + '  };\n'
  + '\n'
  + '  // ── Event delegation helper ──\n'
  + '  _client.listen = function(selector, event, action) {\n'
  + '    document.addEventListener(event, function(e) {\n'
  + '      var el = e.target.closest ? e.target.closest(selector) : null;\n'
  + '      if (el) _client.sendAction(action, { selector: selector, event: event });\n'
  + '    });\n'
  + '  };\n'
  + '\n'
  + '  bw._bwClient = _client;\n'
  + '})(window.bw);\n';
